//! End-to-end golden verification of the BioCLIP 2 image tower against real
//! `open_clip` output, generated by `testdata/make_bioclip_goldens.py`.
//!
//! What this actually pins down is the **preprocessing**, not the ONNX graph.
//! `lrg-ml::bioclip_pre` reimplements pybioclip's transform in Rust, and it
//! differs from `image_pre` on three axes at once — 224 not 384, squash not
//! center-crop, bilinear not bicubic, resize in `f32` not `u8`. Any of those
//! being subtly wrong produces embeddings that still look plausible and
//! classify slightly worse forever. A cosine against real torch output is the
//! only thing that catches it.
//!
//! Requires the exported assets; set `LRG_BIOCLIP_IMAGE_ONNX` (and the taxa
//! files) or place them in `~/.cache/lrgenius/models/`. Skips when not found,
//! like the face goldens — at 834 MB this family is too heavy for every PR.
//! The nightly full-assets job provisions it and sets
//! `LRG_REQUIRE_GOLDENS=all`, which turns that skip into a failure; see
//! `common::assets_ready`.

use lrg_ml::bioclip::{BioclipModel, RANKS};

mod common;

/// The three files this family needs, for the gate's failure message.
fn bioclip_missing(paths: &lrg_ml::bioclip::BioclipModelPaths) -> String {
    format!(
        "BioCLIP assets not found at {} / {} / {}",
        paths.image_onnx.display(),
        paths.taxa_bin.display(),
        paths.taxa_json.display()
    )
}

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    let na: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let nb: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    dot / (na * nb)
}

/// Must match `make_bioclip_goldens.py` / `export_bioclip2_fp16.py` exactly —
/// the goldens store embeddings, not pixels.
fn lcg_bytes(n: usize, seed: u64) -> Vec<u8> {
    let mut out = Vec::with_capacity(n);
    let mut x = seed;
    for _ in 0..n {
        x = (x.wrapping_mul(1103515245).wrapping_add(12345)) & 0x7FFF_FFFF;
        out.push(((x >> 16) & 0xFF) as u8);
    }
    out
}

fn golden_image(name: &str) -> (Vec<u8>, usize, usize) {
    match name {
        "gradient_640x480" => {
            let (w, h) = (640usize, 480usize);
            let n = w * h * 3;
            let pixels = (0..n)
                .map(|i| ((i as f64) * 255.0 / (n - 1) as f64) as u8)
                .collect();
            (pixels, w, h)
        }
        "lcg_noise_800x600" => (lcg_bytes(800 * 600 * 3, 42), 800, 600),
        "small_320x240" => (lcg_bytes(320 * 240 * 3, 99), 320, 240),
        other => panic!("unknown golden image name: {other}"),
    }
}

#[test]
fn image_tower_matches_open_clip() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !common::assets_ready(
        "bioclip",
        paths.image_onnx.is_file(),
        &format!(
            "BioCLIP image tower not found at {}",
            paths.image_onnx.display()
        ),
    ) {
        return;
    }
    let golden_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/bioclip_goldens.json"
    );
    let Ok(raw) = std::fs::read_to_string(golden_path) else {
        // Unlike the model files this one *is* checked in, so its absence is
        // a broken checkout rather than an un-provisioned machine — but it is
        // gated the same way so that one switch covers the whole family.
        // Called for its panic-when-required side effect; the branch returns
        // either way, so the "should I run?" answer has nothing left to decide.
        let _ = common::assets_ready(
            "bioclip",
            false,
            &format!("{golden_path} missing (it is checked in — is the tree intact?)"),
        );
        return;
    };
    let goldens: serde_json::Value = serde_json::from_str(&raw).unwrap();

    let model = BioclipModel::new(paths);
    for (name, entry) in goldens["images"].as_object().unwrap() {
        let (pixels, width, height) = golden_image(name);
        let got = model
            .embed_image(&pixels, width, height)
            .expect("embed_image failed");
        let want: Vec<f32> = entry["embedding"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        assert_eq!(got.len(), want.len(), "{name}: embedding dimension");
        let cos = cosine(&got, &want);
        // Printed, not just asserted: the margin is the interesting number
        // when the resampler or the fp16 export changes, and a bare pass/fail
        // hides a drift from 0.99999 to 0.9991 that is still "green".
        eprintln!("  {name}: cosine {cos:.6}");
        // Measured 0.999998-0.999999 on the shipped export, so `pil_resample`'s
        // bilinear reproduces torchvision's antialiased resize far more closely
        // than "approximately". The threshold sits just under that rather than
        // at a comfortable 0.999: the whole point of this test is catching a
        // preprocessing change, and 0.999 would wave through a resampler that
        // had quietly gone wrong.
        assert!(cos > 0.9999, "{name}: cosine {cos} against open_clip");
    }
}

#[test]
fn classification_is_a_consistent_lineage() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !common::assets_ready("bioclip", paths.all_exist(), &bioclip_missing(&paths)) {
        return;
    }
    let model = BioclipModel::new(paths);
    let (pixels, width, height) = golden_image("lcg_noise_800x600");
    // Warm the session so the timings below measure inference, not model load.
    let _ = model.embed_image(&pixels, width, height).unwrap();
    let t_embed = std::time::Instant::now();
    let mut embedding = model.embed_image(&pixels, width, height).unwrap();
    eprintln!("  embed_image (ViT-L/14) took {:?}", t_embed.elapsed());
    lrg_ml::siglip::l2_normalize(&mut embedding);

    // A confidence floor of 0 forces a call at the deepest rank, so the
    // structural invariants below are exercised even on noise, which no real
    // threshold would ever classify.
    let cfg = lrg_ml::bioclip::ClassifyConfig {
        min_confidence: 0.0,
        top_k: 3,
    };
    // Timed because the head is stored at fp16 and dequantized through a
    // lookup table rather than up-front: this is the number that says whether
    // that trade is still the right one against the ViT forward it sits next
    // to (a few hundred ms).
    let t0 = std::time::Instant::now();
    let pred = model.classify(&embedding, &cfg).unwrap();
    eprintln!("  classify over the full head took {:?}", t0.elapsed());
    let rank = pred.rank.expect("a zero floor must always produce a rank");
    let best = pred.best.expect("a rank implies a best candidate");

    // The chain carries the reported taxon *and its ancestry*, never a bare
    // name. It is `rank + 1` elements minus however many ancestor ranks the
    // dataset leaves blank — 15.6% of the head has at least one, and the bony
    // fish have no `class` at all — so this is an upper bound, not equality.
    let depth = best.taxonomy.split('>').count();
    assert!(
        depth >= 1 && depth <= rank + 1,
        "taxonomy {:?} has {depth} elements at rank {}",
        best.taxonomy,
        RANKS[rank]
    );
    // The blanks must be *dropped*, not rendered: an empty segment would mean
    // a `>>` in the metadata field and an empty keyword in the catalog.
    assert!(
        best.taxonomy.split('>').all(|p| !p.is_empty()),
        "taxonomy {:?} carries an empty segment",
        best.taxonomy
    );
    // ...and the reported rank itself always has a name, which is the whole
    // point of skipping a rank whose winning node is unnamed.
    assert!(!best.scientific_name.is_empty());
    assert!(best.confidence > 0.0 && best.confidence <= 1.0);

    // Alternatives sit at the same rank and never outrank the winner.
    for alt in &pred.alternatives {
        assert!(alt.taxonomy.split('>').all(|p| !p.is_empty()));
        assert!(!alt.scientific_name.is_empty());
        assert!(alt.confidence <= best.confidence);
        assert_ne!(alt.taxonomy, best.taxonomy);
    }
}

/// A confidence floor above 1.0 cannot be met at any rank, which must produce
/// "none" rather than a panic or a bogus kingdom-level call. This is the path
/// every non-organism photo takes.
#[test]
fn an_unreachable_floor_reports_nothing() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !common::assets_ready("bioclip", paths.all_exist(), &bioclip_missing(&paths)) {
        return;
    }
    let model = BioclipModel::new(paths);
    let (pixels, width, height) = golden_image("small_320x240");
    let mut embedding = model.embed_image(&pixels, width, height).unwrap();
    lrg_ml::siglip::l2_normalize(&mut embedding);

    let pred = model
        .classify(
            &embedding,
            &lrg_ml::bioclip::ClassifyConfig {
                min_confidence: 1.1,
                top_k: 3,
            },
        )
        .unwrap();
    assert!(pred.rank.is_none());
    assert!(pred.best.is_none());
    assert_eq!(pred.rank_label(), "none");
}
