//! End-to-end golden verification of the BioCLIP 2 image tower against real
//! `open_clip` output, generated by `testdata/make_bioclip_goldens.py`.
//!
//! What this actually pins down is the **preprocessing**, not the ONNX graph.
//! `lrg-ml::bioclip_pre` reimplements pybioclip's transform in Rust, and it
//! differs from `image_pre` on three axes at once — 224 not 384, squash not
//! center-crop, bilinear not bicubic, resize in `f32` not `u8`. Any of those
//! being subtly wrong produces embeddings that still look plausible and
//! classify slightly worse forever. A cosine against real torch output is the
//! only thing that catches it.
//!
//! Requires the exported assets; set `LRG_BIOCLIP_IMAGE_ONNX` (and the taxa
//! files) or place them in `~/.cache/lrgenius/models/`. Skips when not found,
//! like the face goldens — CI without model assets must not fail here.

use lrg_ml::bioclip::{BioclipModel, RANKS};

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    let na: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let nb: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    dot / (na * nb)
}

/// Must match `make_bioclip_goldens.py` / `export_bioclip2_fp16.py` exactly —
/// the goldens store embeddings, not pixels.
fn lcg_bytes(n: usize, seed: u64) -> Vec<u8> {
    let mut out = Vec::with_capacity(n);
    let mut x = seed;
    for _ in 0..n {
        x = (x.wrapping_mul(1103515245).wrapping_add(12345)) & 0x7FFF_FFFF;
        out.push(((x >> 16) & 0xFF) as u8);
    }
    out
}

fn golden_image(name: &str) -> (Vec<u8>, usize, usize) {
    match name {
        "gradient_640x480" => {
            let (w, h) = (640usize, 480usize);
            let n = w * h * 3;
            let pixels = (0..n)
                .map(|i| ((i as f64) * 255.0 / (n - 1) as f64) as u8)
                .collect();
            (pixels, w, h)
        }
        "lcg_noise_800x600" => (lcg_bytes(800 * 600 * 3, 42), 800, 600),
        "small_320x240" => (lcg_bytes(320 * 240 * 3, 99), 320, 240),
        other => panic!("unknown golden image name: {other}"),
    }
}

#[test]
fn image_tower_matches_open_clip() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !paths.image_onnx.is_file() {
        eprintln!("BioCLIP image tower not found; skipping golden test");
        return;
    }
    let golden_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/bioclip_goldens.json"
    );
    let Ok(raw) = std::fs::read_to_string(golden_path) else {
        eprintln!("bioclip_goldens.json missing; skipping golden test");
        return;
    };
    let goldens: serde_json::Value = serde_json::from_str(&raw).unwrap();

    let model = BioclipModel::new(paths);
    for (name, entry) in goldens["images"].as_object().unwrap() {
        let (pixels, width, height) = golden_image(name);
        let got = model
            .embed_image(&pixels, width, height)
            .expect("embed_image failed");
        let want: Vec<f32> = entry["embedding"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        assert_eq!(got.len(), want.len(), "{name}: embedding dimension");
        let cos = cosine(&got, &want);
        // Printed, not just asserted: the margin is the interesting number
        // when the resampler or the fp16 export changes, and a bare pass/fail
        // hides a drift from 0.99999 to 0.9991 that is still "green".
        eprintln!("  {name}: cosine {cos:.6}");
        // Measured 0.999998-0.999999 on the shipped export, so `pil_resample`'s
        // bilinear reproduces torchvision's antialiased resize far more closely
        // than "approximately". The threshold sits just under that rather than
        // at a comfortable 0.999: the whole point of this test is catching a
        // preprocessing change, and 0.999 would wave through a resampler that
        // had quietly gone wrong.
        assert!(cos > 0.9999, "{name}: cosine {cos} against open_clip");
    }
}

#[test]
fn classification_is_a_consistent_lineage() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !paths.all_exist() {
        eprintln!("BioCLIP assets not found; skipping classification test");
        return;
    }
    let model = BioclipModel::new(paths);
    let (pixels, width, height) = golden_image("lcg_noise_800x600");
    // Warm the session so the timings below measure inference, not model load.
    let _ = model.embed_image(&pixels, width, height).unwrap();
    let t_embed = std::time::Instant::now();
    let mut embedding = model.embed_image(&pixels, width, height).unwrap();
    eprintln!("  embed_image (ViT-L/14) took {:?}", t_embed.elapsed());
    lrg_ml::siglip::l2_normalize(&mut embedding);

    // A confidence floor of 0 forces a call at the deepest rank, so the
    // structural invariants below are exercised even on noise, which no real
    // threshold would ever classify.
    let cfg = lrg_ml::bioclip::ClassifyConfig {
        min_confidence: 0.0,
        top_k: 3,
    };
    // Timed because the head is stored at fp16 and dequantized through a
    // lookup table rather than up-front: this is the number that says whether
    // that trade is still the right one against the ViT forward it sits next
    // to (a few hundred ms).
    let t0 = std::time::Instant::now();
    let pred = model.classify(&embedding, &cfg).unwrap();
    eprintln!("  classify over the full head took {:?}", t0.elapsed());
    let rank = pred.rank.expect("a zero floor must always produce a rank");
    let best = pred.best.expect("a rank implies a best candidate");

    // The chain has exactly one element per rank down to the reported one:
    // that is what makes a "genus" answer mean the genus *and its ancestry*,
    // not a bare name.
    let depth = best.taxonomy.split('>').count();
    assert_eq!(
        depth,
        rank + 1,
        "taxonomy {:?} at rank {}",
        best.taxonomy,
        RANKS[rank]
    );
    assert!(best.confidence > 0.0 && best.confidence <= 1.0);

    // Alternatives sit at the same rank and never outrank the winner.
    for alt in &pred.alternatives {
        assert_eq!(alt.taxonomy.split('>').count(), depth);
        assert!(alt.confidence <= best.confidence);
        assert_ne!(alt.taxonomy, best.taxonomy);
    }
}

/// A confidence floor above 1.0 cannot be met at any rank, which must produce
/// "none" rather than a panic or a bogus kingdom-level call. This is the path
/// every non-organism photo takes.
#[test]
fn an_unreachable_floor_reports_nothing() {
    let paths = lrg_ml::model_paths::resolve_bioclip();
    if !paths.all_exist() {
        eprintln!("BioCLIP assets not found; skipping floor test");
        return;
    }
    let model = BioclipModel::new(paths);
    let (pixels, width, height) = golden_image("small_320x240");
    let mut embedding = model.embed_image(&pixels, width, height).unwrap();
    lrg_ml::siglip::l2_normalize(&mut embedding);

    let pred = model
        .classify(
            &embedding,
            &lrg_ml::bioclip::ClassifyConfig {
                min_confidence: 1.1,
                top_k: 3,
            },
        )
        .unwrap();
    assert!(pred.rank.is_none());
    assert!(pred.best.is_none());
    assert_eq!(pred.rank_label(), "none");
}
