[package]
name = "lrg-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lancedb = "0.37"
futures = "0.3"
serde_json.workspace = true
lrg-chroma-reader.workspace = true
log.workspace = true
chrono.workspace = true
tokio.workspace = true
thiserror = "2"

[dev-dependencies]
tempfile.workspace = true
