//! Spike S3 verification: read a Chroma dir produced by the pinned
//! chromadb 1.5.8 and compare every id, vector, and metadata map against
//! `expected.json`, which was dumped through Chroma's own `collection.get`.
//!
//! Fixtures are generated by scripts in the session scratchpad (see the
//! migration design in the plan); pass the fixture root via
//! CHROMA_FIXTURE_DIRS (colon-separated dirs, each containing
//! `lrgenius.db/` + `expected.json`). Without the env var the test is a
//! no-op so CI without fixtures stays green until M2 checks fixtures in.

use std::collections::HashMap;
use std::path::Path;

use serde_json::Value;

fn check_fixture(dir: &Path) {
    let expected: Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join("expected.json")).expect("expected.json"),
    )
    .unwrap();

    let collections = lrg_chroma_reader::read_chroma_dir(&dir.join("lrgenius.db"))
        .expect("read_chroma_dir failed");

    let by_name: HashMap<&str, &lrg_chroma_reader::ChromaCollection> = collections
        .iter()
        .map(|c| (c.name.as_str(), c))
        .collect();

    for (name, expected_col) in expected.as_object().unwrap() {
        let col = by_name
            .get(name.as_str())
            .unwrap_or_else(|| panic!("collection {name} missing"));
        let expected_records = expected_col["records"].as_object().unwrap();
        assert_eq!(
            col.records.len(),
            expected_col["count"].as_u64().unwrap() as usize,
            "record count mismatch in {name}"
        );

        let mut vectors_checked = 0usize;
        for record in &col.records {
            let exp = expected_records
                .get(&record.id)
                .unwrap_or_else(|| panic!("unexpected id {} in {name}", record.id));

            // Chroma's own get() API does a float32 cosine-normalization
            // round-trip internally, so its output can differ from the raw
            // stored vector by ~1 ulp per element. The reader recovers the
            // raw values (WAL blob / HNSW record), which are the original
            // embedder outputs — compare with a tolerance far below any
            // ranking-relevant scale instead of bit equality.
            let exp_vec: Vec<f32> = exp["embedding"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap() as f32)
                .collect();
            let got_vec = record.embedding.as_ref().unwrap_or_else(|| {
                panic!("no vector recovered for {} in {name}", record.id)
            });
            assert_eq!(got_vec.len(), exp_vec.len(), "dim mismatch for {}", record.id);
            for (a, b) in got_vec.iter().zip(&exp_vec) {
                assert!(
                    (a - b).abs() <= 1e-6 * b.abs().max(1.0),
                    "vector element diverges for {} in {name}: {a} vs {b}",
                    record.id
                );
            }
            vectors_checked += 1;

            let exp_meta = exp["metadata"].as_object().unwrap();
            assert_eq!(
                &record.metadata, exp_meta,
                "metadata mismatch for {} in {name}",
                record.id
            );
        }
        println!("{name}: {vectors_checked} records verified");
    }
}

#[test]
fn fixtures_roundtrip() {
    let Ok(dirs) = std::env::var("CHROMA_FIXTURE_DIRS") else {
        eprintln!("CHROMA_FIXTURE_DIRS not set; skipping fixture verification");
        return;
    };
    for dir in dirs.split(':').filter(|s| !s.is_empty()) {
        println!("--- verifying fixture {dir}");
        check_fixture(Path::new(dir));
    }
}
